### ISSUE TITLE
.well-known

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/api#2]
I don't think that we need this.  7710 gives us an entire URI, as can PvD.

**Comment by tfpauly** [comment]
I agree that we can use the URI from the DHCP option or from PvD. The reason I went this route was to avoid the scheme that was in the API draft to start with, which seemed to be:

- If you access the 7710 URI with a GET, you'll receive the HTTP for the user interactive portal
- If you access the 7710 URI with a POST, you'll get the JSON API

That seemed problematic (a) because it implies the user portal and API are co-located and (b) it seemed overly complex.

Do you have a preference for what methods are valid to access the JSON API, and whether we should specify that the URI needs to be JSON? My concern was that if the DHCP option or whatever pointed to something that was clearly .html, something's wrong, and using a well-known JSON URI to compare against would be a way to detect that.

**Comment by tfpauly** [comment]
@martinthomson Thoughts on the method for fetching the JSON API, or if that's a non-issue?

**Comment by martinthomson** [comment]
Let's take this to the list.

**Comment by darshakthakore** [comment]
PR #6 fixes the well-known URI language. For now there is indication of Accept and Conent-Type header usage but we haven't explicitly called it out until we get a final decision. 
We can close this issue though.
